version: 2

sources:
    - name:
      schema:
      tables:
        - name:
          description: "Tabela que contém dados históricos de commodities"
          columns: Date
          - name: Date
            description: "Data da observação"
          - name: Close
            description: "Preço de fechamento da commodity"
          - name: simbolo
            description: "Símbolo da commodity"

        - name: movimentacao_commodities
          description: "Tabela seed"
          columns:
          - name: date
            description: "Data da transação"
          - name: symbol
            description: "Símbolo da commodity"
          - name: action
            description: "Tipo da transação (buy/sell)"
          - name: quantity
            description: "Quantidade transacionada"
